project_name/models/name_model.py
from project_name import db


class NameModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)

project_name/forms/name_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField


class NameForm(FlaskForm):
    name = StringField('Name')

project_name/__init__.py
import os

from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

basedir = os.path.abspath(os.path.dirname(__file__))


def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.path.join(basedir, 'project_name.db')}"
    app.config['SECRET_KEY'] = 'secret'  # change when creating a new project (use environment variable e.g.)

    from .views import bp_main

    app.register_blueprint(bp_main)

    db.init_app(app)
    Migrate(app, db)

    return app

project_name/views/__init__.py
from project_name.views.main_views import bp_main

project_name/views/main_views.py
from flask import Blueprint, render_template


bp_main = Blueprint('main', __name__, url_prefix='/')


@bp_main.route('/')
def home():
    return render_template('index.html')

project_name/templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
  <a class="navbar-brand" href="{{ url_for('main.home') }}">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">New</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
    </div>
</nav>

<div class="container">

    {% block content %}

    {% endblock %}

</div>

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% endblock %}

</body>
</html>

project_name/templates/index.html
{% extends '_base.html' %}

{% block title %} Homepage {% endblock %}

{% block content %}

<h1>Contents</h1>

{% endblock %}